{
 "title": "Catalog Metrics",
 "tags": [
  "catalog",
  "procureflow",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Requests by Operation",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (operation) (graphql_operation_count_total{module=\"app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Request by Operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (operation) (\n  increase(graphql_operation_count_total{module=\"app\"}[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Time by Operation (ms)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (operation) ( graphql_operation_duration_seconds_sum{module=\"app\"} / graphql_operation_duration_seconds_count{module=\"app\"} ) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time by Operation (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum by (operation) (\n  rate(graphql_operation_duration_seconds_sum{module=\"app\"}[2m]) /\n  rate(graphql_operation_duration_seconds_count{module=\"app\"}[2m])\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}